-- noinspection SqlNoDataSourceInspectionForFile

CREATE TABLE CUSTOMER(
  CUSTOMER_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CUSTOMER_NAME VARCHAR(50) NOT NULL ,
  CUSTOMER_EMAIL  VARCHAR(80) NOT NULL ,
  CUSTOMER_PHONE VARCHAR (15) NOT NULL
);